accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<username>/', views.profile, name='profile')
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/update/', views.update, name='update'),
    path('<int:article_id>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:article_id>/comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
]

auth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

articles/models.py
from django.db import models
# 1번 방식을 위해 필요 from accounts.models import User
from django.conf import settings
# from django.contrib.auth import get_user_model

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()

    # 1. 직접참조 - 해당 방식을 추천하지 않음.
    #user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    # 2. settings.py 변수 활용 - 나는 아마 두 번째 방식을 선호할 것 같네요.
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # # 3. get_user_model
    # user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

class Comment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from .models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta():
        model = User
        fields = ('username',)

class CustomAuthenticationForm(AuthenticationForm):
    pass

articles/forms.py
from django.forms import ModelForm
from .models import Article, Comment

class ArticleForm(ModelForm):
    class Meta():
        model = Article
        exclude = ('user', )

class CommentForm(ModelForm):
    class Meta():
        model = Comment
        fields = ('content', )

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .models import User

# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = CustomUserCreationForm()

        context = {
            'form': form
        }

        return render(request, 'signup.html', context)
    
def login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())

            # /accounts/login
            # /accounts/login/?next=/articles/create/
            next_url = request.GET.get('next')

            #next가 없을 때 => None or 'articles:index'
            #next가 있을 때 => 'articles/create' or 'articles:index'
            return redirect(next_url or 'articles:index')

    else:
        form = CustomAuthenticationForm()

        context = {
            'form':form,
        }
        return render(request, 'login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

def profile(request, username):
    user_profile = User.objects.get(username=username)

    context = {
        'user_profile':user_profile,
    }
    return render(request, 'profile.html', context)

articles/views.py
from django.shortcuts import render, redirect
from .forms import ArticleForm, CommentForm
from .models import Article, Comment
from accounts.models import User
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def create(request):
    if request.method=='POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:index')
    else:
        form = ArticleForm()
        context = {
            'form':form,
        }
    return render(request, 'create.html', context)

def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }

    return render(request, 'index.html', context)

def detail(request, id):
    article = Article.objects.get(id=id)
    form = CommentForm()
    context = {
        'article': article,
        'form': form,
    }

    return render(request, 'detail.html', context)

@login_required
def delete(request, id):
    article = Article.objects.get(id=id) 

    if article.user == request.user:
        article.delete()

        return redirect('articles:index')

    else:
        return redirect('articles:detail', article.id)

@login_required
def update(request, id):
    article = Article.objects.get(id=id) 
    
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if article.user == request.user:
            if form.is_valid():
                form.save()

        return redirect('articles:detail', article.id)
    else:
        form = ArticleForm(instance=article)
        context = {
            'form':form,
        }
        return render(request, 'update.html', context)
        
@login_required
def comment_create(request, article_id):
    form = CommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)

        # #객체를 저장하는 경우
        # comment.user = request.user
        # article = Article.objects.get(id=article_id)
        # comment.article = article

        #id값을 저장하는 경우
        comment.user_id = request.user.id
        comment.article_id = article_id

        comment.save()

        return redirect('articles:detail', id=article_id)

@login_required
def comment_delete(request, article_id, comment_id):
    comment = Comment.objects.get(id=comment_id)
    if request.user == comment.user:
        comment.delete()
    
    return redirect('articles:detail', id=article_id)

accounts/templates/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-success">로그인</button>
    </form>
{% endblock %}

accounts/templates/profile.html
{% extends 'base.html' %}

{% block body %}
    <h1>{{user_profile.username}}</h1>

    {% for article in user_profile.article_set.all %}
        <li>{{article.title}}</li>
    {% endfor %}
{% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-success">회원가입</button>
</form>
{% endblock %}

articles/templates/create.html
{% extends 'base.html' %}

{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="btn btn-primary">게시글 작성</button>
    </form>
{% endblock %}

articles/templates/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}   
    <br>
    <h3>제목:{{article.title}}</h3>
    <hr>
    <p>{{article.content}}</p>
    <br>
    <p>작성자:{{article.user}}</p>
    <hr>
    <form action="{% url 'articles:comment_create' article.id %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-success">댓글 달기</button>
    </form>
    <hr>
    {% for comment in article.comment_set.all %}
        <li>{{comment.user.username}} - {{comment.content}}</li>
        {% if user == comment.user %}
            <a href="{% url 'articles:comment_delete' article.id comment.id %}">댓글 삭제</a>
        {% endif %}
    {% endfor %}
    <hr>
    <a href="{% url 'articles:index'%}" type="botton" class="btn btn-primary">게시판으로</a>
    {% if user == article.user %}
        <a href="{% url 'articles:update' article.id %}" type="botton" class="btn btn-warning">게시글 수정</a>
        <a href="{% url 'articles:delete' article.id %}" type="botton" class="btn btn-danger">게시글 삭제</a>
    {% endif %}

{% endblock %}

articles/templates/error.html
{% extends 'base.html' %}

{% block body %}
<h5>오류입니다.</h5>
<a href="{% url 'articles:detail' article.id %}" type="botton" class="btn btn-secondary">게시글로 돌아가기</a>
{% endblock %}

articles/templates/index.html
{% extends 'base.html' %}

{% block body %}
<br>
    <h1>게시물</h1>
    <hr>
    {% for article in articles %}
    <h3>{{article.title}}</h3>
    <br>
    <p>작성자:{{article.user}}</p>
    <a href="{% url 'articles:detail' article.id %}" type="botton" class="btn btn-primary">게시글로</a>
    <a href="{% url 'articles:update' article.id %}" type="botton" class="btn btn-warning">수정</a>
    <a href="{% url 'articles:delete' article.id %}" type="botton" class="btn btn-danger">삭제</a>



    <hr>
    {% endfor %}

{% endblock %}

articles/templates/update.html
{% extends 'base.html' %}

{% block body %}   
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="btn btn-success">수정 완료</button>
    </form>
<hr>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="nav">
        <a href="{% url 'articles:index' %}" class="nav-link">home</a>
        {% if user.is_authenticated %}
            <a href="{% url 'accounts:profile' user.username %}" class="nav-link">{{user}}</a>
            <a href="{% url 'articles:create' %}" class="nav-link">create</a>
            <a href="{% url 'accounts:logout' %}" class="nav-link">logout</a>
        {% else %}
            <a href="{% url 'accounts:signup' %}" class="nav-link">signup</a>
            <a href="{% url 'accounts:login' %}" class="nav-link">login</a>
        {% endif %}  


    </nav>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>